# Generated by Django 5.2.4 on 2025-07-15 05:22

import affiliates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SolicitudAfiliacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                        verbose_name="Estado de la Solicitud",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Afiliación",
                "verbose_name_plural": "Solicitudes de Afiliación",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudPersonaJuridica",
            fields=[
                (
                    "solicitudafiliacion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="affiliates.solicitudafiliacion",
                    ),
                ),
                (
                    "ruc_empresa",
                    models.CharField(
                        max_length=13, unique=True, verbose_name="RUC de la Empresa"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=255, verbose_name="Dirección"),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=255, verbose_name="Razón Social"),
                ),
                (
                    "nombre_comercial",
                    models.CharField(max_length=255, verbose_name="Nombre Comercial"),
                ),
                (
                    "logotipo_empresa",
                    models.ImageField(
                        upload_to=affiliates.models.obtener_ruta_adjunto_persona_juridica,
                        verbose_name="Logotipo de la Empresa",
                    ),
                ),
                (
                    "cedula_representante_legal",
                    models.CharField(
                        max_length=10, verbose_name="Cédula del Representante Legal"
                    ),
                ),
                (
                    "nombre_completo_representante_legal",
                    models.CharField(
                        max_length=200,
                        verbose_name="Nombres y Apellidos del Representante Legal",
                    ),
                ),
                (
                    "correo_electronico_representante_legal",
                    models.EmailField(
                        max_length=254,
                        verbose_name="Correo Electrónico del Representante",
                    ),
                ),
                (
                    "celular_representante_legal",
                    models.CharField(
                        max_length=20, verbose_name="Celular del Representante"
                    ),
                ),
                (
                    "archivo_ruc_empresa",
                    models.FileField(
                        upload_to=affiliates.models.obtener_ruta_adjunto_persona_juridica,
                        verbose_name="Archivo de RUC de la Empresa",
                    ),
                ),
                (
                    "archivo_escritura_constitucion",
                    models.FileField(
                        upload_to=affiliates.models.obtener_ruta_adjunto_persona_juridica,
                        verbose_name="Archivo de Escritura de Constitución",
                    ),
                ),
                (
                    "archivo_cedula_representante",
                    models.FileField(
                        upload_to=affiliates.models.obtener_ruta_adjunto_persona_juridica,
                        verbose_name="Archivo de Cédula del Representante",
                    ),
                ),
                (
                    "numeros_contacto_whatsapp",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Números de WhatsApp",
                    ),
                ),
                (
                    "url_sitio_web",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL del Sitio Web"
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Persona Jurídica",
                "verbose_name_plural": "Solicitudes de Personas Jurídicas",
            },
            bases=("affiliates.solicitudafiliacion",),
        ),
        migrations.CreateModel(
            name="SolicitudPersonaNatural",
            fields=[
                (
                    "solicitudafiliacion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="affiliates.solicitudafiliacion",
                    ),
                ),
                (
                    "cedula",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Cédula de Identidad"
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="RUC",
                    ),
                ),
                ("nombres", models.CharField(max_length=100, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                (
                    "correo_electronico",
                    models.EmailField(
                        max_length=254, verbose_name="Correo Electrónico"
                    ),
                ),
                (
                    "numero_celular",
                    models.CharField(max_length=20, verbose_name="Número de Celular"),
                ),
                (
                    "archivo_cedula",
                    models.FileField(
                        upload_to=affiliates.models.obtener_ruta_adjunto_persona_natural,
                        verbose_name="Archivo de Cédula de Identidad",
                    ),
                ),
                (
                    "archivo_ruc",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=affiliates.models.obtener_ruta_adjunto_persona_natural,
                        verbose_name="Archivo de RUC (opcional)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Persona Natural",
                "verbose_name_plural": "Solicitudes de Personas Naturales",
            },
            bases=("affiliates.solicitudafiliacion",),
        ),
    ]
